# Generated by Django 5.0.4 on 2024-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attempts',
            field=models.IntegerField(default=6),
        ),
    ]
