# Generated by Django 5.0.4 on 2024-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_player_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attempts',
            field=models.IntegerField(default=5),
        ),
    ]
