# Generated by Django 5.0.4 on 2024-04-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_player_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='attempts',
            field=models.IntegerField(default=6),
        ),
    ]
